// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdknamkvstwuihynclbr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impka25hbWt2c3R3dWloeW5jbGJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MjI4NjEsImV4cCI6MjA2MTA5ODg2MX0.RZPpni8q-TIdg3G4ZjDQO6LT1fcm60TQqe-oO1ROMXs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);